name: Download Artifact
on: workflow_dispatch

jobs:
  making_artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: create file 
        run: echo "artifact created on $(date)" > artifact.txt

      - name: upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: example.txt
          path: artifact.txt
  
  download_artifact:
    needs: making_artifact
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: example-artifact
        
    
